
DROP TABLE IF EXISTS MARCA;
DROP TABLE IF EXISTS PRODUCTO;
DROP SEQUENCE IF EXISTS PRODUCTO_ID_SEQ;
DROP SEQUENCE IF EXISTS MARCA_ID_SEQ;
CREATE SEQUENCE PRODUCTO_ID_SEQ INCREMENT BY 1;
CREATE SEQUENCE MARCA_ID_SEQ INCREMENT BY 1;

CREATE TABLE MARCA("ID" numeric(38,0) NOT NULL , "CODE" VARCHAR2(20 CHAR) NOT NULL , "DESCRIPTION" VARCHAR2(255) NOT NULL , "DATA_CREACIO" TIMESTAMP (6), "DATA_MODIFICACIO" TIMESTAMP (6) , "USUARI_CREACIO" VARCHAR2(200) , "USUARI_MODIFICACIO" VARCHAR2(200), CONSTRAINT "MARCA_PK" PRIMARY KEY (ID));
CREATE TABLE PRODUCTO( "ID" numeric(38,0) NOT NULL ,"MARCA_ID" numeric(38,0) NOT NULL ,"START_DATE" TIMESTAMP (6),"END_DATE" TIMESTAMP (6), "PRICE_LIST" numeric(38,0), "PRODUCT_DESC" VARCHAR2(255),  "PRICE" numeric(18,2), "CURR" VARCHAR2(8 CHAR), CONSTRAINT "PRODUCTO_PK" PRIMARY KEY (ID));

ALTER TABLE PRODUCTO ADD FOREIGN KEY (MARCA_ID) REFERENCES MARCA(ID);


--MARCA
INSERT INTO MARCA ("ID", "CODE", "DESCRIPTION","DATA_CREACIO","DATA_MODIFICACIO","USUARI_CREACIO","USUARI_MODIFICACIO") VALUES(MARCA_ID_SEQ.NEXTVAL,'MR1','MARCA 1',CURRENT_DATE,CURRENT_DATE,'USER 1',null);
INSERT INTO MARCA ("ID", "CODE", "DESCRIPTION","DATA_CREACIO","DATA_MODIFICACIO","USUARI_CREACIO","USUARI_MODIFICACIO") VALUES(MARCA_ID_SEQ.NEXTVAL,'MR2','MARCA 2',CURRENT_DATE,CURRENT_DATE,'USER 1',null);
INSERT INTO MARCA ("ID", "CODE", "DESCRIPTION","DATA_CREACIO","DATA_MODIFICACIO","USUARI_CREACIO","USUARI_MODIFICACIO") VALUES(MARCA_ID_SEQ.NEXTVAL,'MR3','MARCA 3',CURRENT_DATE,CURRENT_DATE,'USER 1',null);

--PRODUCTO
INSERT INTO PRODUCTO ("ID", "MARCA_ID", "START_DATE", "END_DATE","PRICE_LIST","PRODUCT_DESC","PRICE","CURR") VALUES(PRODUCTO_ID_SEQ.NEXTVAL,1,  {ts '2020-06-14 00:00:00.00'},  {ts '2020-12-31 23:59:59.00'} ,1,'Descripcion 1',35.50,'EUR');
INSERT INTO PRODUCTO ("ID", "MARCA_ID", "START_DATE", "END_DATE","PRICE_LIST","PRODUCT_DESC","PRICE","CURR") VALUES(PRODUCTO_ID_SEQ.NEXTVAL,1,  {ts '2020-06-14 15:00:00.00'}, {ts '2020-06-14 18:30:00.00'},2,'Descripcion 2',25.45,'EUR');
INSERT INTO PRODUCTO ("ID", "MARCA_ID", "START_DATE", "END_DATE","PRICE_LIST","PRODUCT_DESC","PRICE","CURR") VALUES(PRODUCTO_ID_SEQ.NEXTVAL,1,  {ts '2020-06-15 00:00:00.00'}, {ts '2020-06-15 11:00:00.00'},3,'Descripcion 3',30.50,'EUR');
INSERT INTO PRODUCTO ("ID", "MARCA_ID", "START_DATE", "END_DATE","PRICE_LIST","PRODUCT_DESC","PRICE","CURR") VALUES(PRODUCTO_ID_SEQ.NEXTVAL,1,  {ts '2020-06-15 16:00:00.00'}, {ts '2020-12-31 23:59:59.00'},4,'Descripcion 4',38.95,'EUR');